#ifndef KERN_SYSCALL_H
#define KERN_SYSCALL_H

/* syscalls will have sys_ as its prefix, some of them will be fake. */
#define sys_none    0
#define	sys_exit    1
/* #define sys_fork    2 */
#define	sys_read    3
#define	sys_write   4
#define	sys_open    5
#define	sys_close   6
#define	sys_wait4   7
/* #define	sys_link    9 */
/* #define	sys_unlink  10 */
#define	sys_chdir   12
#define	sys_fchdir  13
#define	sys_mknod   14
#define	sys_chmod   15
/* #define	sys_chown   16 */
#define	sys_break   17
#define	sys_getfsstat   18
#define	sys_getpid  20
#define	sys_ptrace  26
#define	sys_recvmsg 27
#define	sys_sendmsg 28
#define	sys_recvfrom    29
#define	sys_accept  30
#define	sys_getpeername 31
#define	sys_getsockname 32
#define	sys_access  33
/* It seems no need to support file flags... */
/* #define	sys_chflags 34 */
/* #define	sys_fchflags    35 */
#define	sys_sync    36
#define	sys_kill    37
#define	sys_getppid 39
#define	sys_dup     41
#define	sys_pipe    42
#define	sys_profil  44
#define	sys_ktrace  45
#define	sys_sigaction   46
#define	sys_sigprocmask 48
#define	sys_acct    51
#define	sys_sigpending  52
#define	sys_sigaltstack 53
#define	sys_ioctl   54
#define	sys_reboot  55
#define	sys_revoke  56
/* And no symbolic links for simplicity. */
/* #define	sys_symlink 57 */
/* #define	sys_readlink    58 */
#define	sys_execve  59
#define	sys_umask   60
#define	sys_msync   65
#define	sys_sbrk	69
#define	sys_sstk	70
#define	sys_vadvise	72
#define	sys_munmap	73
#define	sys_mprotect	74
#define	sys_madvise	75
#define	sys_setitimer	83
#define	sys_swapon	85
#define	sys_getitimer	86
#define	sys_getdtablesize	89
#define	sys_dup2	90
#define sys_fcntl   92
#define	sys_select	93
#define	sys_setpriority	96
/* syscall on networking will be supported in uxxx_net module. */
#define	sys_socket	97
#define	sys_connect	98
#define	sys_getpriority	100
#define	sys_sigreturn	103
#define	sys_bind	104
#define	sys_setsockopt	105
#define	sys_listen	106
#define	sys_sigsuspend	111
#define	sys_vtrace	115
#define	sys_gettimeofday	116
#define	sys_getrusage	117
#define	sys_getsockopt	118
#define	sys_resuba	119
#define	sys_readv	120
#define	sys_writev	121
#define	sys_settimeofday	122
#define	sys_fchown	123
#define	sys_fchmod	124
#define	sys_rename	128
#define	sys_flock	131
#define	sys_mkfifo	132
#define	sys_sendto	133
#define	sys_socketpair	135
#define	sys_mkdir	136
#define	sys_rmdir	137
#define	sys_utimes	138
#define	sys_adjtime	140
#define	sys_setsid	147
#define	sys_quotactl	148
#define	sys_nfssvc	155
#define	sys_statfs	157
#define	sys_fstatfs	158
#define	sys_getfh	161
#define	sys_shmsys	171
#define	sys_stat	188
#define	sys_fstat	189
#define	sys_lstat	190
#define	sys_getdirentries	196
#define	sys_mmap	197
#define	sys_lseek	199
#define	sys_truncate	200
#define	sys_ftruncate	201

/* Prototypes of syscall functions. */
typedef int sys_none();  
typedef int sys_exit();  
typedef int sys_fork(); 
typedef int sys_read(); 
typedef int sys_write();
typedef int sys_open();
typedef int sys_close();
typedef int sys_wait4();
typedef int sys_link();
typedef int sys_unlink();
typedef int sys_chdir();
typedef int sys_fchdir();
typedef int sys_mknod();
typedef int sys_chmod();
typedef int sys_chown();
typedef int sys_break();
typedef int sys_getfsstat();
typedef int sys_getpid();
typedef int sys_ptrace();
typedef int sys_recvmsg();
typedef int sys_sendmsg();
typedef int sys_recvfrom();
typedef int sys_accept();
typedef int sys_getpeername();
typedef int sys_getsockname();
typedef int sys_access();
typedef int sys_chflags();
typedef int sys_fchflags();
typedef int sys_sync();
typedef int sys_kill();
typedef int sys_getppid();
typedef int sys_dup();
typedef int sys_pipe();
typedef int sys_profil();
typedef int sys_ktrace();
typedef int sys_sigaction();
typedef int sys_sigprocmask();
typedef int sys_acct();
typedef int sys_sigpending();
typedef int sys_sigaltstack();
typedef int sys_ioctl();
typedef int sys_reboot();
typedef int sys_revoke();
typedef int sys_symlink();
typedef int sys_readlink();
typedef int sys_execve();
typedef int sys_umask();
typedef int sys_msync();
typedef int sys_sbrk();
typedef int sys_sstk();
typedef int sys_vadvise();
typedef int sys_munmap();
typedef int sys_mprotect();
typedef int sys_madvise();
typedef int sys_setitimer();
typedef int sys_swapon();
typedef int sys_getitimer();
typedef int sys_getdtablesize();
typedef int sys_dup2();
typedef int sys_fcntl();
typedef int sys_select();
typedef int sys_setpriority();
typedef int sys_socket();
typedef int sys_connect();
typedef int sys_getpriority();
typedef int sys_sigreturn();
typedef int sys_bind();
typedef int sys_setsockopt();
typedef int sys_listen();
typedef int sys_sigsuspend();
typedef int sys_vtrace();
typedef int sys_gettimeofday();
typedef int sys_getrusage();
typedef int sys_getsockopt();
typedef int sys_resuba();
typedef int sys_readv();
typedef int sys_writev();
typedef int sys_settimeofday();
typedef int sys_fchown();
typedef int sys_fchmod();
typedef int sys_rename();
typedef int sys_flock();
typedef int sys_mkfifo();
typedef int sys_sendto();
typedef int sys_socketpair();
typedef int sys_mkdir();
typedef int sys_rmdir();
typedef int sys_utimes();
typedef int sys_adjtime();
typedef int sys_setsid();
typedef int sys_quotactl();
typedef int sys_nfssvc();
typedef int sys_statfs();
typedef int sys_fstatfs();
typedef int sys_getfh();
typedef int sys_shmsys();
typedef int sys_stat();
typedef int sys_fstat();
typedef int sys_lstat();
typedef int sys_getdirentries();
typedef int sys_mmap();
typedef int sys_lseek();
typedef int sys_truncate();
typedef int sys_ftruncate();

#endif
